### ISSUE TITLE
Travis CI + Netlify workflow

### ISSUE THREAD

**Issue by apreshill** [rstudio-education/stat545#1]
Still not entirely sure what worked and what did not, but these are my breadcrumbs for next time...

1. Make a new Netlify site from GitHub repo via browser

2. If first time doing this at all, locally install Netlify CLI via terminal

```
brew install node # install nodejs first via homebrew
npm install netlify-cli -g # then install cli for netlify
netlify login # via browser pop-up
```

3. For each new site, do:

```
netlify link
```

From Jenny's notes: "This produced `.netlify/state.json`, which holds the (non-secret) site id. Apparently this can also be provided via a travis env var named `NETLIFY_SITE_ID` (ok to reveal in the log)."

What did not work was: (a) setting the netlify site link with a text file called [`.netlify`](https://github.com/dgrtwo/tidy-text-mining/blob/master/.netlify); or (b) using the `"path":"_book"` in that file either (conclude that you should use the `.travis.yml` below to set the `--dir _book` instead).

4. [Obtain a Token in the Netlify UI](https://www.netlify.com/docs/cli/#authentication)

5. In Travis:
    - enable continuous integration for your book’s GitHub repo on Travis
    - save the Netlify token from step 4 as a [`NETLIFY_AUTH_TOKEN`](https://www.netlify.com/docs/cli/#authentication) environment variable.

6. Following [Sean Kross' instructions for adding Travis to a bookdown](http://seankross.com/2016/11/17/How-to-Start-a-Bookdown-Book.html)
    - add `.Rbuildignore`
    - add `DESCRIPTION`
    - add `.travis.yml`:

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

before_install:
- npm install netlify-cli -g

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

after_success:
- netlify deploy --prod --dir _book
```

7. Modify `.gitignore` to include: 
    - `_book` (unless you had changed the bookdown default `output_dir` to [something else](https://bookdown.org/yihui/bookdown/configuration.html))
    - `_bookdown_files`

8. add, commit, and push these files.

Lots of help from @jennybc's notes:

jennybc/whattheyforgot#25

And from here:

rstudio/bookdown#459

And here:
dgrtwo/tidy-text-mining#42

**Comment by apreshill** [comment]
Another option from @ismayc:

1. Have travis build book, then push to a different branch (`target_branch: gh-pages`); [travis docs here](https://docs.travis-ci.com/user/deployment/pages/)

1. Have Netlify deploy from *that* branch (`gh-pages`), not master.

[https://github.com/moderndive/moderndive_book/blob/master/.travis.yml](https://github.com/moderndive/moderndive_book/blob/master/.travis.yml)

**Comment by ismayc** [comment]
My settings in Netlify in case that wasn't clear. 
![screenshot 2018-09-25 12 24 20](https://user-images.githubusercontent.com/9215614/48097280-4dd33500-e1ce-11e8-80cd-758a85a37854.png)

**Comment by hammer** [comment]
Thanks for writing this up! I used your directions to get a deploy of `bookdown-demo` working: https://github.com/hammer/test-book. One thing I noticed was that the PDF and EPUB downloads weren't working, so I changed `bookdown::render_book("index.Rmd")` to `rmarkdown::render_site(encoding = 'UTF-8')` in `.travis.yml`.

I'm not sure if this approach is preferred over repeated invocations of `bookdown::render_book` (the approach [taken](https://github.com/rstudio/bookdown-demo/blob/master/_build.sh) by Yihui in `bookdown-demo`), so I've [asked on StackOverflow](https://stackoverflow.com/questions/53309328/bookdownrender-book-vs-rmarkdownrender-site-to-build-all-outputs).

Either way, I thought others like me who come to this issue seeking guidance may benefit from what I've learned about PDF and EPUB building today.

Thanks again and apologies if the above information is redundant for you!

**Comment by rudeboybert** [comment]
@ismayc work setting up GitHub + Travis CI + [Netlify](https://www.netlify.com/) integration has been total cash money. Being able to fix typos in the source `.Rmd` only and then publish on the web w/o rebuilding the book locally has been a yooge time saver @ajohns24 @milesott

Also @apreshill, I'm sure you're already 76 steps ahead of me, but people would ❤️a tutorial on integrating bookdown + Travis CI that's in a similar vein as your [Up and running with blogdown](https://alison.rbind.io/post/up-and-running-with-blogdown/) tutorial! I loved it, my advanced students loved it, everyone loved it! Dunno if you have the bandwidth to write one up, but I'm sure it would equally sell like 🔥🍰!

**Comment by apreshill** [comment]
Huzzah this worked!

new `_travis.yml`

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files

script:
- Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  keep-history: true
  github_token: $stat545_GITHUB_PAT
  target_branch: gh-pages
  on:
    all_branches: true
```

<img width="913" alt="screen shot 2018-12-08 at 8 30 02 pm" src="https://user-images.githubusercontent.com/12160301/49693451-12f35280-fb28-11e8-8acd-2be1cda567b3.png">
